---
title: "p8105_hw5_jy3186"
author: "Jiayi Yang"
date: "2022-11-10"
output: github_document
---

```{r setup, include=FALSE}
library(readxl)
library(tidyverse)
```

## Problem 1
Import and tidy the dataset
```{r, message = FALSE}
homicide_df = 
  read_csv(url("https://github.com/washingtonpost/data-homicides/blob/master/homicide-data.csv?raw=true"))
```

Create a city_state variable (e.g. “Baltimore, MD”) and then summarize within cities to obtain the total number of homicides and the number of unsolved homicides (those for which the disposition is “Closed without arrest” or “Open/No arrest”).

```{r}
homicide_new =
homicide_df %>% 
  mutate(city_state = str_c(city, state, sep = ", ")) %>% 
  group_by(city_state)

homicide_count = 
  homicide_new %>% 
  group_by(city_state) %>% 
  summarize(homicide_total = n())

homicide_unsolved =
  homicide_new %>% 
  filter(disposition %in% c("Closed without arrest", "Open/No arrest")) %>% 
  group_by(city_state) %>% 
  summarize(unsolved_total = n())

homicide_table = 
  merge(homicide_count, homicide_unsolved, by = "city_state")

knitr::kable(homicide_table)
```

